language: generic

sudo: required 
services:
 - docker

before_install:
 - docker build -t hazem-react -f Dockerfile-dev .

script:
 - docker run -e CI=true hazem-react npm run test

deploy: 
 provider: elasticbeanstalk
 region: us-east-2
 app: "dockerApplication"
 env: "Dockerapplication-env"
 bucket_name: "elasticbeanstalk-us-east-2-854620429039"
 bucket_path: "dockerApplication"
 on:
  branch: master
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key: &3
    secure: $AWS_SECRET_KEY