language: generic
sudo: required 
services:
 - docker

before_install:
 - docker build -t hazem-react -f Dockerfile-dev .

script:
 - docker run -e CI=true hazem-react npm run test

deploy:
 
 skip_cleanup: true 
 provider: elasticbeanstalk
 region: eu-west-3
 app: "DockerApplication"
 env: "Dockerapplication-env"
 bucket_name: "elasticbeanstalk-eu-west-3-854620429039"
 bucket_path: "DockerApplication"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: 
  secure: $AWS_SECRET_KEY